name: expo install --fix

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1,13 * * *'

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - run: corepack enable yarn

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn expo install --fix
        working-directory: ./app

      - id: app_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ vars.KEYCHAIN_BOT_APP_ID }}
          private_key: ${{ secrets.KEYCHAIN_BOT_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ steps.app_token.outputs.token }}
          commit-message: 'bump(deps): `expo install --fix`'
          title: 'bump(deps): `expo install --fix`'
          committer: Keychain Bot <githubapp+349640@users.noreply.github.com>
          author: Keychain Bot <githubapp+349640@users.noreply.github.com>
          body: |
            #### What this PR does / why we need it:

            Bump expo dependencies to newest release with `expo install --fix`, this command also fixes `./app/package.json` and `./app/app.json` files to patch any non-compliant dependencies.
          branch: keychain-bot/expo-install-fixes
